### PR TITLE
Fix #237, fix #242: Re-add toolbar icon reset workaround.

### LINKED ISSUE #237: The green badge is not displayed if opening a product's link in a new tab
[Affected versions]:
- Firefox Release v63.0 

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the latest version of the "Price Wise" add-on (8.0.0) downloaded from ([download link](https://testpilot.firefox.com/files/shopping-testpilot@mozilla.org/latest)). 

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to Walmart website.
3. Middle click on a product.
4. Wait for the products's page to load and click on the newly opened tab.
5. Observe the Price Wise badge.

[Expected result]:
- The green badge is displayed.

[Actual result]:
- The initial state badge is displayed.

[Notes]:
- This issue is reproducible only with the Walmart website.
- This is also reproducible when opening the link from the context menu.
- Here is a screen recording of the issue:

badge disappear

### LINKED ISSUE #242: "Add This Product" button becomes active only after a few secconds on slow connections.
I have verified this issue using the latest version of the Price Wise (8.0.0-signed) version and the issue is still reproducible on https://www.walmart.com/, using a slow Internet connection. The "Add This Product" button is briefly active after the page is fully loaded and after that is no longer active.

However, on https://www.homedepot.com/, after the page is fully loaded, the "Add This Product" button becomes active only after a few secconds. 

In order to test this I have simulated a slow Internet connection using the "Network Link Conditioner" app.,on Mac, and also with the functionality from RDM mode.
Attached is a screen recording of the issue:
 
slowinternet

_Originally posted by @Softvision-RemusDranca in https://github.com/mozilla/price-wise/issues/192#issuecomment-435089865_

### PR DESCRIPTION
**Pull request by Osmose**

### CODE REVIEW

File: src/background/index.js [hunk 1]
```diff
@@ -65,6 +65,18 @@ import {registerEvents, handleWidgetRemoved} from 'commerce/telemetry/extension'
...
+  // script in case subframe loads clear the toolbar icon.
+  // TODO(osmose): Remove once Firefox 64 hits the release channel.
+  browser.webRequest.onCompleted.addListener(
+    (details) => {
+      if (details.tabId) {
+        browser.tabs.sendMessage(details.tabId, {type: 'resend-product'});
+      }
+    },
+    {urls: ['https://*/*', 'http://*/*'], types: ['sub_frame']},
+  );
```
Comment (biancadanforth) [inline src/background/index.js]: I recall you had originally had something like this before implementing the `resend` stuff -- why did you switch to `resend` originally?

File: src/extraction/index.js [hunk 2]
```diff
@@ -43,6 +43,10 @@ function extractProduct() {
 }
 
 async function sendProductToBackground(extractedProduct) {
+  if (!extractedProduct) {
+    return null;
```
[the remark this answers is not in the document]
Comment (Osmose) [reply src/extraction/index.js]: It's an async function so a promise is always returned; if we don't call return, it just returns `undefined`. But yes, this is to appease the eslint rule.

File: src/background/index.js (hunk 1 above)
Comment (Osmose) [reply src/background/index.js]: The issue is intermittent, and I suspect QA verified on a version that actually didn't have the fix (because I was slow to release it), then replicated the issue and re-filed. I'm not entirely sure how I was able to replicate it off of master, but at this point the fix is so consistent that I'm trying not to question it.
