### PR TITLE
Fix #256: Change popup width in overflow menu

### LINKED ISSUE #256: [Linux] A blank space is displayed on the right side of the door hanger after pinning the Price Wise toolbar button in the Overflow Menu
[Affected versions]:
- Firefox Release v63.0.1 and up

[Affected Platforms]:
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest version of the "Price Wise" add-on (10.0.0) downloaded from ([download link](https://testpilot.firefox.com/files/shopping-testpilot@mozilla.org/latest)). 
- The Price Wise button was pinned to the Overflow Menu.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the "More tools..." toolbar button and select the "Tracked Products" option.
3. Observe the UI of the "Price Watcher List".

[Expected result]:
- The door hanger is correctly displayed, without any UI issues.

[Actual result]:
- A blank space is displayed on the right side of the door hanger.

[Notes]:
- This issue is also reproducible when there are products in the Price Wise list.
- Here is a screen recording of the issue:

linux issue

### PR DESCRIPTION
**Pull request by biancadanforth**
With CustomizableUI.jsm (via the experimental `browser.customizableUI` API added in #157), it is possible to detect when the browserAction toolbar button is and is not in the Overflow menu.

Because the overflow menu width varies by OS (for example, it is 377px wide on my Mac 10.13 and 425px wide on a Linux 14.04 (see screenshots below for confirmation)), this patch will detect whether or not the toolbar button is in the Overflow menu and adjust the width accordingly.

This fix has the added benefit of allowing us to constrain the non-Overflow menu popup width (which is hopefully the vast majority use case) to the UX spec of 320px where previously we had set it to a max-width of 400px to try to accommodate Overflow menu issues.

**Verified issue on Linux 14.04 (v11.0.0 prior to this patch!) in Firefox Nightly 65 and Release 63 shows that the popup width exceeds our CSS specified max-width of 400px**
256-overflow-menu
256-overflow-menu-2

### CODE REVIEW

**Comment by biancadanforth** [comment]
@Osmose Ready for your review!

I confirmed that the issue was that the overflow menu on Linux exceeds 400px. It was 425px, so our previous `max-width` of 400px was too small.

File: src/experiment_apis/customizableUI/api.js [hunk 1]
```diff
@@ -5,6 +5,7 @@
 
 this.customizableUI = class extends ExtensionAPI {
   getAPI(context) {
+    const {Services} = ChromeUtils.import('resource://gre/modules/Services.jsm');
```
[the remark this answers is not in the document]
Comment (biancadanforth) [reply src/experiment_apis/customizableUI/api.js]: Nope; I will remove the second argument from the other one. Good catch.

**Comment by biancadanforth** [comment]
@Osmose Ready for another look!

I had to add another check for the overflow menu in the case of pinning/unpinning (a "fixed" overflow menu), as it was only working on window resize (an "unfixed" overflow menu) which are apparently in two different areas of the chrome per jaws.

File: src/browser_action/index.jsx [hunk 2]
```diff
@@ -20,6 +20,12 @@ if (extractedProductJSON) {
   appProps.extractedProduct = JSON.parse(extractedProductJSON);
 }
 
+(async function checkOverflow() {
+  if (await browser.customizableUI.isWidgetInOverflow('shopping-testpilot_mozilla_org-browser-action')) {
+    document.getElementById('browser-action-app').classList.add('overflow');
```
Comment (Osmose) [inline src/browser_action/index.jsx]: Hmmm, maybe we could put this into one of the React components, like in the state for `BrowserActionApp`? Not sure if that adds much to this.

File: src/experiment_apis/customizableUI/api.js [hunk 3]
```diff
@@ -25,6 +26,14 @@ this.customizableUI = class extends ExtensionAPI {
             };
           },
         ).api(),
+        async isWidgetInOverflow(widgetId) {
+          const {area} = CustomizableUI.getPlacementOfWidget(widgetId);
+          const browserWindow = Services.wm.getMostRecentWindow('navigator:browser');
+          // First check is for the non-fixed overflow menu (e.g. widget moved by resizing window)
+          // Second is for fixed overflow menu (e.g. widget moved by (un)pinning button to overflow)
+          return (CustomizableUI.getWidget(widgetId).forWindow(browserWindow).overflowed
+            || area === 'widget-overflow-fixed-list');
```
Comment (Osmose) [inline src/experiment_apis/customizableUI/api.js]: This becomes slightly more readable IMO if we format this like this:

```js
return (
  CustomizableUI.getWidget(widgetId).forWindow(browserWindow).overflowed
  || area === 'widget-overflow-fixed-list'
);
```

File: src/browser_action/index.jsx (hunk 2 above)
Comment (biancadanforth) [reply src/browser_action/index.jsx]: I tried to do this just now, but `<BrowserActionApp />` currently returns a `<React.Fragment>`, which doesn't accept a class name. Wrapping the whole thing in a `<div>` instead and adding the class to that is possible, but then the CSS also needs another layer instead of applying the `overflow` class directly to `#browser-action-app`:

```css
#browser-action-app > div {
  width: 320px;
}

#browser-action-app > div.overflow {
  width: 100%;
}
```

Also with the new Study Invitation screen (#274 ), I'd need that wrapper `div` in two places in BrowserActionApp instead of just one.

I also tried putting the class name directly on `<BrowserActionApp />` in `index.jsx`, but `ReactDOM.render` didn't like the `await` keyword needed for `browser.customizableUI.isWidgetInOverflow`.

I think for simplicity, I'll just leave this as is for now. Perhaps we can refactor this later if we ever implement the view router pattern you suggested [here](https://github.com/mozilla/price-wise/pull/278#discussion_r234744740)... The options I can think of/try right now seem more confusing and more prone to bugs.
